- name: restart nova-services
  service: name={{ item }} state=restarted enabled=yes
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-spicehtml5proxy
    - nova-serialproxy

