- name: ensure nova packages are installed
  apt: pkg={{ item }}
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - python-novaclient
    - nova-consoleproxy

- name: ensure nova sqlite is deleted
  file: dest=/var/lib/nova/nova.sqlite state=absent
    
# - name: ensure api-paste.ini is present
#   copy: >
#     src=etc/nova/api-paste.ini 
#     dest=/etc/nova/api-paste.ini 
#     owner=nova 
#     group=nova 
#     mode=0660 
#     backup=yes
#   notify: 
#   - restart nova-services

- name: ensure nova.conf file is present
  template: >
    src=etc/nova/nova.conf
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0660
  notify: 
  - restart nova-services

