- name: ensure nova packages are installed
  apt: name={{ item }}
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - python-novaclient
    - nova-consoleproxy
    - nova-novncproxy

- name: ensure nova sqlite is deleted
  file: dest=/var/lib/nova/nova.sqlite state=absent
    
- name: ensure nova.conf file is present
  template: >
    src=etc/nova/nova.conf
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0660
  notify: 
  - restart nova-services

- name: ensure default nova-consoleproxy file is present
  template: >
    src=etc/default/nova-consoleproxy
    dest=/etc/default/nova-consoleproxy
    owner=root
    group=root
    mode=0644
  notify: 
  - restart nova-services

- name: ensure nova_api db is initialized
  command: /usr/bin/nova-manage api_db sync
  notify: 
  - restart nova-services

- name: ensure nova db is initialized
  command: /usr/bin/nova-manage db sync
  notify: 
  - restart nova-services

