- name: ensure heat packages are installed
  apt: name={{ item }}
  with_items:
    - heat-api 
    - heat-api-cfn 
    - heat-engine 

- name: ensure heat sqlite is deleted
  file: dest=/var/lib/heat/heat.sqlite state=absent

- name: ensure heat.conf file is up to date
  template: >
    src=etc/heat/heat.conf
    dest=/etc/heat/heat.conf
    owner=heat
    group=heat
    mode=0600
  notify:
  - restart heat-services

# - name: ensure heat_init.sh script is transfered
#   template: >-
#     src=root/heat_init.sh
#     dest=/root/heat_init.sh
#     owner=root
#     group=root
#     mode=750
    
# - name: ensure heat domain is created
#   shell: /root/heat_init.sh
#   register: stack_user_domain_id

# - name: ensure heat domain id is added to heat.conf
#   ini_file: >-
#     dest=/etc/heat/heat.conf
#     section=DEFAULT
#     option=stack_user_domain_id
#     value={{ stack_user_domain_id.stdout }}
    
- name: ensure heat db is initialized
  command: /usr/bin/heat-manage db_sync
  notify:
  - restart heat-services

