- name: ensure python-sqlalchemy < 0.10 is installed
  apt: name=python-sqlalchemy default_release=jessie

- name: ensure python-cryptography (>=1.0) is installed (backport BUG)
  apt: name=python-cryptography default_release=testing state=latest
  
- name: ensure keystone packages are installed
  apt: name={{ item }} default_release=jessie-backports
  with_items:
    - keystone
    - python-keystone
    - python-keystoneclient
    - python-oslo.db
  notify: start keystone
  
- name: ensure sqlite keystone database is deleted
  file: dest=/var/lib/keystone/keystone.db state=absent

- name: ensure keystone config script is present
  template: >
    src=etc/keystone/keystone.conf
    dest=/etc/keystone/keystone.conf
    owner=keystone
    group=keystone
    mode=0600

- name: DB sync for keystone
  shell: >
    /usr/bin/keystone-manage db_sync
  notify: restart keystone
