- name: ensure placement-api, apache2 and mod-wsgi-py3 are installed
  apt: name={{ item }}
  loop:
    - placement-api
    - apache2
    - libapache2-mod-wsgi-py3

- name: ensure placement database connection is configured
  ini_file:
    path: /etc/placement/placement.conf
    section: placement_database
    option: connection
    value: mysql+pymysql://placement:{{ placement_db_password }}@{{ internal_ip }}/placement
  notify:
  - restart apache2

- name: ensure keystone_authtoken is configured
  ini_file:
    path: /etc/placement/placement.conf
    section: keystone_authtoken
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "www_authenticate_uri", value: 'http://{{ controller_fqdn }}:5000' }
    - { option: "auth_url", value: 'http://{{ controller_fqdn }}:5000' }
    - { option: "memcached_servers", value: '{{ controller_fqdn }}:11211' }
    - { option: "auth_type", value: password }
    - { option: "project_domain_name", value: Default}
    - { option: "user_domain_name", value: Default}
    - { option: "project_name", value: service}
    - { option: "username", value: placement}
    - { option: "password", value: "{{ placement_identity_password }}" }
    - { option: "region", value: "{{ region }}" }    
  notify:
  - restart apache2

- name: ensure auth_strategy is set to keystone
  ini_file:
    path: /etc/placement/placement.conf
    section: api
    option: auth_strategy
    value: keystone
  notify:
  - restart apache2

- name: ensure placement db is initialized
  command: /usr/bin/placement-manage db sync
  notify:
  - restart apache2

- name: ensure placement-api service is stopped and disabled
  service: name=placement-api state=stopped enabled=no

- name: ensure wsgi-placement.conf is present
  template:
    src: etc/apache2/sites-available/wsgi-placement.conf
    dest: /etc/apache2/sites-available/wsgi-placement.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2

- name: ensure virtual host wsgi is enabled
  shell: /usr/sbin/a2ensite wsgi-placement.conf
  notify: restart apache2
