- name: restart neutron agents
  service: name={{ item }} state=restarted
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-openvswitch-agent
    
- name: restart openvswitch services
  service: name=openvswitch-switch state=restarted

