# Not needed since UTF-8 is properly defined into database conf file
#
# - name: ensure migrate_version table is in UTF-8
#   command: mysql -u glance -h {{ controller_ip }} -p{{ root_db_password }} -e 'alter table migrate_version convert to character set utf8 collate utf8_unicode_ci;' glance
#   ignore_errors: yes

- name: ensure glance db is initialized
  command: /usr/bin/glance-manage db_sync
  
# Using glance_image module (ansible >= 1.2)
- name: ensure cirros image is added to glance
  glance_image: >
    auth_url=http://{{ controller_ip }}:5000/v2.0/
    copy_from={{ img_url }}
    name={{ img_name }}
    container_format=bare
    disk_format=qcow2
    state=present
    login_username=demo
    login_tenant_name=demo
    login_password={{ demo_pass }}
    region_name={{ region }}
