- name: ensure br-int switch is created
  openvswitch_bridge: bridge=br-int state=present
  notify: restart ovs agent

- name: ensure br-ex switch is created
  openvswitch_bridge: bridge=br-ex state=present
  notify: restart ovs agent

- name: ensure br-ex_setup.sh script is copied to the network-node
  template: >-
    src=root/br-ex_setup.sh
    dest=/root/br-ex_setup.sh
    owner=root
    group=root
    mode=750

- name: ensure external interface is properly configured
  command: /root/br-ex_setup.sh

- name: ensure br-ex is configured and external interface added permanently
  template: >-
    src=etc/network/interfaces
    dest=/etc/network/interfaces
    owner=root
    group=root mode=0644

