- name: ensure br-int switch is created
  openvswitch_bridge: bridge=br-int state=present
  notify: restart ovs agent
  
- name: ensure br-ex switch is created
  openvswitch_bridge: bridge=br-ex state=present
  notify: restart ovs agent

# From /usr/share/doc/neutron-common
- name: ensure br-ex is set as an external bridge
  command: ovs-vsctl br-set-external-id br-ex bridge-id br-ex

- name: ensure default routing rule is deleted
  command: /sbin/ip route del default via {{ external_gateway }} dev {{ ext_net_nic }}
  ignore_errors: True

- name: ensure IP address is deleted from external nic
  command: /sbin/ip addr del {{ controller_external_ip }}/{{ controller_external_CIDR }} dev {{ ext_net_nic }}

- name: ensure external interface is added to br-ex
  openvswitch_port: bridge=br-ex port={{ ext_net_nic }} state=present
  notify: restart neutron agents

- name: ensure IP address is added to external bridge
  command: /sbin/ip addr add {{ controller_external_ip }}/{{ controller_external_CIDR }} dev br-ex

# Then your br-ex IP address is handled by your network config in your
# /etc/network/interfaces configuration file:

# auto br-ex
# iface br-ex inet static
#         address 192.168.1.10
#         netmask 255.255.255.0

# This will bring up a bridge "br-int" for the internal network, and "br-ex" for
# the network connected to the public internet. Here, 192.168.1.10 is then of
# course your public IP address of the router which will deliver network to your
# virtual machines.

- name: ensure br-ex is configured and external interface added permanently
  template: >-
    src=etc/network/interfaces
    dest=/etc/network/interfaces
    owner=root group=root mode=0644
  notify: restart network

- name: ensure default openvswitch-switch init are deleted
  command: update-rc.d -f openvswitch-switch remove

- name: ensure openvswitch-switch is modified
  template: >-
    src=etc/init.d/openvswitch-switch
    dest=/etc/init.d/openvswitch-switch
    owner=root group=root mode=755

- name: ensure default openvswitch-switch init are created
  command: /sbin/insserv openvswitch-switch 

- name: ensure neutron database is absent
  mysql_db: name=neutron state=absent

- name: ensure neutron database is present
  mysql_db: name=neutron

- name: ensure neutron database is reinitialized
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

