- name: Ensure sources.list file is properly defined 
  template: >
    src=etc/apt/sources.list
    dest=/etc/apt/sources.list
    owner=root
    group=root
    mode=0644

- name: Ensure apt-pinning is set properly 
  copy: >
    src=etc/apt/preferences
    dest=/etc/apt/preferences
    owner=root
    group=root
    mode=0644
  
- name: Ensure system is upgraded (It can take a long time)
  apt: upgrade=yes update_cache=yes



- name: Ensure ntp is installed
  apt: name=ntp default_release=jessie
  notify: restart ntp

# - name: Ensure /etc/hosts is properly defined
#   copy: >-
#     src=etc/hosts
#     dest=/etc/hosts
#     owner=root
#     group=root
#     mode=0644