- name: Ensure mysql server and mysql python client are installed
  apt: pkg={{ item }}
  with_items:
    - python-mysqldb
    - mysql-server

- name: Ensure mysql binds to internal interface
  template: >
    src=etc/my.cnf 
    dest=/etc/mysql/my.cnf 
    owner=root 
    group=root 
    mode=0644
  notify: restart mysql

# http://dev.mysql.com/doc/refman/5.6/en/default-privileges.html
- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host=localhost
    password={{ root_db_password }}

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: copy .my.cnf file with root password credentials
  template: >
    src=root/.my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: update mysql root password for all root accounts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ root_db_password }}
  with_items:
    - "{{ controller_ip }}"
    - 127.0.0.1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - "{{ controller_ip }}"
    - "{{ inventory_hostname_short }}"
    - 127.0.0.1
    - ::1

