- name: Ensure mariadb server and python-pymysql are installed
  apt: name={{ item }}
  loop:
    - mariadb-server
    - python-pymysql
    
- name: Ensure 99-openstack.cnf is present
  template:
    src: etc/mysql/mariadb.conf.d/99-openstack.cnf
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: root
    group: root
    mode: 664
  notify: restart mariadb

# http://dev.mysql.com/doc/refman/5.6/en/default-privileges.html
- name: set mariadb root password
  mysql_user: 
    name: root
    password: "{{ root_db_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: copy .my.cnf file with root password credentials
  template:
    src: "root/.my.cnf"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ root_db_password }}"
  loop:
    - "{{ controller_ip }}"
    - "localhost"
    - 127.0.0.1

