- name: restart neutron-server
  service: name=neutron-server state=restarted

- name: restart ovs-agent
  service: name=neutron-plugin-openvswitch-agent state=restarted
  
- name: restart neutron agents
  service: name=$item state=restarted
  with_items:
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-lbaas-agent
    - neutron-metadata-agent
    
- name: restart openvswitch services
  service: name=openvswitch-switch state=restarted

